spring:
  application:
    name: MedicalAppointmentSchedule
  datasource:
    url: jdbc:postgresql://localhost:5432/MedicalAppointment
    username: postgres
    password: postgres
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
       time-to-live: 60000
    main:
      allow-bean-definition-overriding: true
    jackson:
      stream-write-constraints:
        max-nesting-depth: 2000